package fullcontact

import (
	"strings"
	"testing"

	assert "github.com/stretchr/testify/require"
)

func TestPersonEnrich(t *testing.T) {
	ch := make(chan *APIResponse)
	// respJson = "{\"fullName\":\"Marquita H Ross\",\"ageRange\":\"37-47\",\"gender\":\"Female\",\"location\":\"San Francisco, California, United States\",\"title\":\"Senior Petroleum Manager\",\"organization\":\"Mostow Co.\",\"twitter\":\"https://twitter.com/marqross91\",\"linkedin\":\"https://www.linkedin.com/in/marquita-ross-5b6b72192\",\"facebook\":null,\"bio\":\"Senior Petroleum Manager at Mostow Co.\",\"avatar\":\"https://img.fullcontact.com/sandbox/1gagrO2K67_oc5DLG_siVCpYVE5UvCu2Z.png\",\"website\":\"http://marquitaas8.com/\",\"details\":{\"name\":{\"given\":\"Marquita\",\"family\":\"Ross\",\"full\":\"Marquita H Ross\"},\"age\":{\"range\":\"35-44\",\"value\":42},\"gender\":\"Female\",\"household\":{\"familyInfo\":{\"totalAdults\":2,\"totalChildren\":1,\"totalPeopleInHousehold\":3},\"homeInfo\":{\"dwellingType\":\"Multi Family Dwelling/Apartment\",\"homeValueEstimate\":513,\"loanToValueEstimate\":4},\"locationInfo\":{\"seasonalAddress\":true,\"carrierRoute\":\"PO Box\",\"designatedMarketArea\":\"807\",\"coreBasedStatisticalArea\":\"41860 - San Francisco-Oakland-Hayward, CA Metropolitan Statistical Area\",\"nielsenCountySize\":\"B - All counties in the next largest set of metropolitan areas which toher account for 30% of U.S. households according to the 2000 Census. No non-metropolitan counties qualify as A or B counties.\",\"congressionalDistrict\":\"14\",\"numericCountyCode\":222},\"presence\":{\"multigenerationalResident\":\"PRESENT\",\"children\":\"PRESENT\"},\"finance\":{\"discretionaryIncomeEstimate\":45,\"financialDebtRangeEstimate\":\"$0\",\"householdIncomeEstimate\":\"$150,000 - $199,999\",\"netWorthRange\":\"$50,000 - $74,999\",\"cashValueBalanceHouseholdEstimate\":\"$25,000 - $49,999\"}},\"demographics\":{\"gender\":\"Female\",\"age\":{\"range\":\"35-44\",\"value\":42},\"livingStatus\":\"Probable Homeowner\",\"maritalStatus\":\"MARRIED\",\"occupation\":\"Professional - Engineer/Industrial\"},\"survey\":{\"own\":{\"ownDigitalCamera\":true,\"ownDog\":true,\"ownSwimmingPool\":true,\"ownRv\":true},\"collectibles\":{\"general\":true,\"coins\":true,\"stamps\":true},\"creditCards\":{\"premium\":{\"amex\":true,\"store\":true,\"visaOrMasterCard\":true},\"regular\":{\"amex\":true,\"other\":true,\"visaOrMasterCard\":true},\"debit\":true},\"dietConcerns\":{\"general\":true,\"loseWeight\":true,\"vitaminSupplements\":true,\"healthy\":true},\"hobby\":{\"general\":true,\"baking\":true,\"cigarSmoking\":true,\"gourmetCooking\":true,\"cooking\":true,\"gardening\":{\"general\":true,\"flowers\":true},\"homeImprovement\":true,\"exercise3xPerWeek\":true,\"lowFatCooking\":true,\"diy\":true,\"spirituality\":true},\"onlinePurchaser\":true,\"investments\":true,\"music\":{\"general\":true,\"christianOrGospel\":true,\"classical\":true,\"other\":true,\"rhythmAndBlues\":true},\"reading\":{\"likesToRead\":true,\"bibleOrDevotional\":true,\"bestSellingFiction\":true,\"childrens\":true,\"history\":true,\"health\":true,\"naturalHealthRemedies\":true,\"entertainment\":true,\"worldNewsOrPolitics\":true,\"bestSellers\":true,\"magazines\":true},\"sporting\":{\"fitness\":true,\"walking\":true,\"running\":true},\"travel\":{\"general\":true,\"usBusiness\":true,\"casinoVacations\":true,\"frequentFlyer\":true},\"religious\":true,\"electronics\":{\"appleDevice\":true,\"cableTv\":true,\"highSpeedInternet\":true,\"dvdPlayer\":true,\"hdtv\":true,\"homeTheater\":true,\"other\":true},\"purchase\":{\"homeDecorating\":true,\"beautyProducts\":true,\"clubStores\":true,\"usesCoupons\":true}},\"finance\":{\"bankCard\":\"Multiple Bank Card\",\"activeLineOfCredit\":true,\"retailCard\":\"Multiple Retail Card\"},\"census\":{\"basicTractNumber\":145,\"basicBlockGroup\":2,\"year2010\":{\"educationLevel\":\"High School Diploma\",\"average\":{\"numberOfCarsInHousehold\":2.3000000000000003},\"percent\":{\"abovePovertyLevel\":74,\"belowPovertyLevel\":28,\"black\":17,\"blueCollarEmployed\":35,\"divorcedOrSeparated\":14,\"hispanic\":43,\"homesBuiltSince2000\":52,\"homeowner\":90,\"householdsWithChildren\":38,\"married\":36,\"mobileHome\":45,\"movedToAreaSince2000\":21,\"salariedProfessional\":35,\"singleFamilyHome\":43,\"vehicleOwnership\":84,\"white\":35},\"median\":{\"ageOfHouseholder\":23,\"effectiveBuyingIncome\":18,\"homeValue\":35,\"householdIncome\":18,\"householdIncomeByState\":69},\"populationDensity\":{\"centileInState\":67,\"centileInUs\":17},\"socioEconomicScore\":29}},\"buyer\":{\"catalog\":{\"payment\":{\"amx\":true,\"creditCard\":true,\"houseCharge\":true,\"masterCard\":true,\"retailCard\":true,\"visa\":true},\"apparel\":{\"general\":true,\"children\":true,\"men\":true,\"mensBigTall\":true,\"nonGenderSpecific\":true,\"womenPetiteSize\":true,\"womenPlusSize\":true},\"beauty\":true,\"books\":true,\"childrenProducts\":true,\"electronics\":true,\"furniture\":true,\"health\":true,\"jewelry\":true,\"music\":true,\"stationery\":true,\"travel\":true,\"videoEntertainment\":true},\"retail\":{\"apparel\":{\"general\":true,\"children\":true,\"women\":true},\"beauty\":true,\"books\":true,\"childrenProducts\":true,\"collectibles\":true,\"foodBeverages\":true,\"gift\":true,\"health\":true,\"homeFurnishings\":true,\"jewelry\":true,\"music\":true,\"stationery\":true,\"travel\":true}},\"emails\":[],\"phones\":[],\"profiles\":{\"twitter\":{\"username\":\"marqross91\",\"url\":\"https://twitter.com/marqross91\",\"bio\":\"Senior Petroleum Manager at Mostow Co.\",\"service\":\"twitter\"},\"pinterest\":{\"username\":\"marquitaross006\",\"url\":\"http://www.pinterest.com/marquitaross006/\",\"bio\":\"Senior Petroleum Manager at Mostow Co.\",\"service\":\"pinterest\"},\"linkedin\":{\"username\":\"marquita-ross-5b6b72192\",\"userid\":\"761326554\",\"url\":\"https://www.linkedin.com/in/marquita-ross-5b6b72192\",\"bio\":\"Senior Petroleum Manager at Mostow Co.\",\"service\":\"linkedin\"}},\"locations\":[{\"city\":\"San Francisco\",\"region\":\"California\",\"regionCode\":\"CA\",\"country\":\"United States\",\"countryCode\":\"US\",\"formatted\":\"San Francisco, California, United States\"}],\"employment\":[{\"name\":\"Mostow Co.\",\"current\":true,\"title\":\"Senior Petroleum Manager\",\"start\":{\"year\":2019,\"month\":9}}],\"photos\":[{\"label\":\"avatar\",\"value\":\"https://img.fullcontact.com/sandbox/1gagrO2K67_oc5DLG_siVCpYVE5UvCu2Z.png\"}],\"education\":[{\"name\":\"University of California, Berkeley\",\"degree\":\"Bachelors\",\"end\":{\"year\":1998}}],\"urls\":[{\"value\":\"http://marquitaas8.com/\"}],\"interests\":[]},\"extended\":{\"epsilon_key_1\": \"9\",\"epsilon_key_2\": \"H\",\"epsilon_key_3\": \"Q\",\"epsilon_key_4\": \"0\",\"epsilon_key_5\": \"11\"},\"isSandboxProfile\":true,\"updated\":\"1970-01-01\"}"
	respJson := "{\"fullName\":\"Marquita H Ross\",\"ageRange\":\"37-47\",\"gender\":\"Female\",\"location\":\"San Francisco, California, United States\",\"title\":\"Senior Petroleum Manager\",\"organization\":\"Mostow Co.\",\"twitter\":\"https://twitter.com/marqross91\",\"linkedin\":\"https://www.linkedin.com/in/marquita-ross-5b6b72192\",\"facebook\":null,\"bio\":\"Senior Petroleum Manager at Mostow Co.\",\"avatar\":\"https://img.fullcontact.com/sandbox/1gagrO2K67_oc5DLG_siVCpYVE5UvCu2Z.png\",\"website\":\"http://marquitaas8.com/\",\"details\":{\"name\":{\"given\":\"Marquita\",\"family\":\"Ross\",\"full\":\"Marquita H Ross\"},\"age\":{\"range\":\"35-44\",\"value\":42},\"gender\":\"Female\",\"household\":{\"familyInfo\":{\"householdSize\":\"3\",\"numberOfAdults\":\"2\",\"numberOfChildren\":\"1\",\"lifeCycles\":{\"babyBoomers\":\"babyBoomers\",\"dualIncomeNoKids\":\"dualIncomeNoKids\",\"familyTies\":\"familyTies\",\"generationX\":\"generationX\",\"millenials\":\"millenials\",\"millenialsButFirstLetMeTakeASelfie\":\"millenialsButFirstLetMeTakeASelfie\",\"millenialsGettinHitched\":\"millenialsGettinHitched\",\"millenialsIAmAnAdult\":\"millenialsIAmAnAdult\",\"millenialsLivesWithMom\":\"millenialsLivesWithMom\",\"millenialsMomLife\":\"millenialsMomLife\",\"millenialsPuttingDownRoots\":\"millenialsPuttingDownRoots\"}},\"homeInfo\":{\"dwellingType\":\"Multi Family Dwelling/Apartment\",\"dwellingTypeIndicator\":\"yes\",\"householdEducation\":\"no\",\"householdEducationIndicator\":\"yes\",\"maritalStatus\":\"single\",\"lengthOfResidence\":\"3\",\"lengthOfResidenceIndicator\":\"yes\",\"affluents\":\"no\",\"currentLoanToValue\":\"100000\",\"homeHeatSource\":\"yes\",\"householdOccupation\":\"no\",\"familyComposition\":\"2\",\"homeMarketValue\":\"100000\",\"ownerToOwner\":\"no\",\"rentertoOwner\":\"no\",\"yearHomeBuilt\":\"2022\"},\"locationInfo\":{\"carrierRoute\":\"PO Box\",\"blockGroupNumber\":\"807\",\"coreBasedStatisticalArea\":\"41860 - San Francisco-Oakland-Hayward, CA Metropolitan Statistical Area\",\"nielsenCountySize\":\"B - All counties in the next largest set of metropolitan areas which toher account for 30% of U.S. households according to the 2000 Census. No non-metropolitan counties qualify as A or B counties.\",\"nielsenCountySizeCode\":\"B\",\"censusTractSuffix\":\"SFF\",\"dsfSeasonCode\":\"455\",\"countyCode\":\"US\"},\"presence\":{\"presenceOfChildren\":\"PRESENT\",\"presenceOfChildrenIndicator\":\"PRESENT\",\"adult\":{\"age18to24\":\"1\",\"age25to34\":\"2\",\"age35to44\":\"3\",\"age45to54\":\"4\",\"age55to64\":\"5\",\"age65to74\":\"6\",\"age75above\":\"7\"},\"child\":{\"age0to2\":\"1\",\"age3to5\":\"2\",\"age6to10\":\"3\",\"age11to15\":\"4\",\"age16to17\":\"5\"}},\"finance\":{\"income\":\"45\",\"incomeIndicator\":\"yes\",\"narrowBandIncome\":\"20 Million\",\"discretionarySpendingIncome\":\"50 Million\",\"firstMortgageAmountInThousands\":\"200\",\"homeEquityLoanDate\":\"24/10/2022\",\"homeMarketValueTaxRecord\":\"yes\",\"homeEquityLoanInThousands\":\"10\",\"homeEquityLoanIndicator\":\"yes\",\"investmentResources\":\"10 Million\",\"liquidResources\":\"1 Million\",\"mortgageInterestRateTypeOrRefinance\":\"10\",\"mortgageLiability\":\"200K\",\"mortgageLoanTypeOrRefinance\":\"no\",\"mortgageDate\":\"20/10/2021\",\"refinanceIndicator\":\"no\",\"secondMortgageAmountInThousands\":\"0\",\"shortTermLiability\":\"10K\",\"incomeIndex\":\"10\",\"netWorth\":\"70 Million\",\"wealthResources\":\"no\",\"paymentMethodCreditCard\":\"yes\"}},\"demographics\":{\"gender\":\"Female\",\"consumers\":{\"valueScore\":\"100\"},\"homeInfo\":{\"homeOwner\":\"yes\",\"homeOwnerIndicator\":\"yes\"},\"enthusiasts\":{\"niches\":\"no\",\"politicalParty\":\"democratic\"},\"maritalInfo\":{\"maritalStatus\":\"SINGLE\",\"maritalStatusIndicator\":\"yes\"},\"age\":{\"range\":\"35-44\",\"value\":42,\"birthday\":{\"year\":2020,\"month\":1,\"day\":1},\"ageIn2YearRanges\":\"40-42\",\"exactAge\":\"42\"}},\"surveys\":{\"other\":{\"electronics\":\"true\",\"grandchildren\":\"true\",\"militaryVeteran\":\"true\",\"onlineHousehold\":\"true\",\"scienceAndNewTechnology\":\"true\",\"swimmingPool\":\"true\"},\"social\":{\"facebookUser\":\"true\",\"instagramUser\":\"true\",\"pinterestUser\":\"true\",\"twitterUser\":\"true\"},\"own\":{\"smartPhone\":\"true\",\"cat\":\"true\",\"dog\":\"true\",\"pets\":\"true\"},\"collectibles\":{\"dolls\":\"true\",\"figurines\":\"true\",\"any\":\"true\",\"artAntique\":\"true\",\"clubContinuity\":\"true\"},\"dietConcerns\":{\"naturalFoods\":\"true\",\"diet\":\"true\",\"weightControl\":\"true\"},\"hobby\":{\"baking\":\"true\",\"cigarSmoking\":\"true\",\"crafts\":\"true\",\"cooking\":\"true\",\"gardening\":\"true\",\"homeStudyCourses\":\"true\",\"quilting\":\"true\",\"selfImprovementCourses\":\"true\",\"woodworking\":\"true\",\"photography\":\"true\",\"careerAdvancementCourses\":\"true\",\"any\":\"true\",\"automotiveWork\":\"true\",\"birdFeedingOrWatching\":\"true\",\"culturalArtsOrEvents\":\"true\",\"gourmetFoods\":\"true\",\"homeImprovementOrDIY\":\"true\",\"motorcycleRiding\":\"true\",\"scrapbooking\":\"true\",\"sewingOrNeedleworkOrKnitting\":\"true\",\"wine\":\"true\"},\"mailOrder\":{\"any\":\"true\",\"apparel\":\"true\",\"books\":\"true\",\"buyer\":\"true\",\"childrensProducts\":\"true\",\"food\":\"true\",\"gifts\":\"true\",\"healthOrBeautyProducts\":\"true\",\"homeFurnishing\":\"true\",\"jewelry\":\"true\",\"videosOrDVD\":\"true\",\"womensPlusApparel\":\"true\"},\"investments\":{\"juvenileLifeInsurance\":\"true\",\"burialInsurance\":\"true\",\"insurance\":\"true\",\"investments\":\"true\",\"lifeInsurance\":\"true\",\"medicareCoverage\":\"true\",\"mutualFunds\":\"true\",\"stocksOrBonds\":\"true\"},\"music\":{\"country\":\"true\",\"christianOrGospel\":\"true\",\"classical\":\"true\",\"jazz\":\"true\",\"any\":\"true\",\"rhythmAndBlues\":\"true\",\"rockNRoll\":\"true\"},\"reading\":{\"fashion\":\"true\",\"bibleOrDevotional\":\"true\",\"bestSellingFiction\":\"true\",\"childrens\":\"true\",\"military\":\"true\",\"romance\":\"true\",\"sports\":\"true\",\"books\":\"true\",\"cookingOrCulinary\":\"true\",\"countryOrLifestyle\":\"true\",\"interior\":\"true\",\"entertainment\":\"true\",\"medicalOrHealth\":\"true\",\"worldNews\":\"true\"},\"sporting\":{\"campingOrHiking\":\"true\",\"fishing\":\"true\",\"golf\":\"true\",\"nascar\":\"true\",\"boatingOrSailing\":\"true\",\"cycling\":\"true\",\"fitnessExcercise\":\"true\",\"bigGameHunting\":\"true\",\"huntingOrShooting\":\"true\",\"sportsMerchandiseOrActivewearRecency\":\"true\",\"runningOrJogging\":\"true\",\"skiingOrSnowboarding\":\"true\",\"sportsParticipation\":\"true\",\"walkingForHealth\":\"true\",\"yogaOrPilates\":\"true\"},\"travel\":{\"timeshare\":\"true\",\"business\":\"true\",\"cruiseShipVacation\":\"true\",\"international\":\"true\",\"leisure\":\"true\",\"rvVacations\":\"true\",\"travelInTheUSA\":\"true\",\"traveler\":\"true\"},\"donor\":{\"activeMilitary\":\"true\",\"animalWelfare\":\"true\",\"artsOrCultural\":\"true\",\"cancer\":\"true\",\"catholic\":\"true\",\"childrens\":\"true\",\"charitable\":\"true\",\"humanitarian\":\"true\",\"nativeAmerican\":\"true\",\"otherReligious\":\"true\",\"politicalConservative\":\"true\",\"politicalLiberal\":\"true\",\"veteran\":\"true\",\"wildlifeEnvironmental\":\"true\",\"worldRelief\":\"true\"},\"purchase\":{\"artsCraftsRecency\":\"true\",\"beautyAndSpaRecency\":\"true\",\"beveragesRecency\":\"true\",\"booksRecency\":\"true\",\"clubContinuity\":\"true\",\"homeDecorRecency\":\"true\",\"gardenAndBackyardRecency\":\"true\",\"sweepstakes\":\"true\",\"maleApparelRecency\":\"true\",\"musicVideosRecency\":\"true\",\"specialtyFoodsAndGiftsRecency\":\"true\",\"sportsAndOutdoorRecency\":\"true\",\"toolsAndElectronicsRecency\":\"true\",\"femaleAndMaleRecency\":\"true\",\"femaleBrandAndFitRecency\":\"true\"}},\"emails\":[],\"phones\":[],\"profiles\":{\"twitter\":{\"username\":\"marqross91\",\"url\":\"https://twitter.com/marqross91\",\"bio\":\"Senior Petroleum Manager at Mostow Co.\",\"service\":\"twitter\"},\"pinterest\":{\"username\":\"marquitaross006\",\"url\":\"http://www.pinterest.com/marquitaross006/\",\"bio\":\"Senior Petroleum Manager at Mostow Co.\",\"service\":\"pinterest\"},\"linkedin\":{\"username\":\"marquita-ross-5b6b72192\",\"userid\":\"761326554\",\"url\":\"https://www.linkedin.com/in/marquita-ross-5b6b72192\",\"bio\":\"Senior Petroleum Manager at Mostow Co.\",\"service\":\"linkedin\"}},\"locations\":[{\"city\":\"San Francisco\",\"region\":\"California\",\"regionCode\":\"CA\",\"country\":\"United States\",\"countryCode\":\"US\",\"formatted\":\"San Francisco, California, United States\"}],\"employment\":[{\"name\":\"Mostow Co.\",\"current\":true,\"title\":\"Senior Petroleum Manager\",\"start\":{\"year\":2019,\"month\":9}}],\"photos\":[{\"label\":\"avatar\",\"value\":\"https://img.fullcontact.com/sandbox/1gagrO2K67_oc5DLG_siVCpYVE5UvCu2Z.png\"}],\"education\":[{\"name\":\"University of California, Berkeley\",\"degree\":\"Bachelors\",\"end\":{\"year\":1998}}],\"urls\":[{\"value\":\"http://marquitaas8.com/\"}],\"interests\":[]},\"extended\":{\"epsilon_key_1\":\"9\",\"epsilon_key_2\":\"H\",\"epsilon_key_3\":\"Q\",\"epsilon_key_4\":\"0\",\"epsilon_key_5\":\"11\"},\"isSandboxProfile\":true,\"updated\":\"1970-01-01\"}"
	fcTestClient, testServer := getTestServerAndClient(personEnrichUrl, respJson, 200)
	defer testServer.Close()
	go fcTestClient.do(testServer.URL, nil, ch)
	resp := <-ch
	response := resp.PersonResponse

	assert.True(t, resp.IsSuccessful)
	assert.Equal(t, 200, resp.StatusCode)
	assert.Equal(t, "200 OK", resp.Status)
	assert.True(t, strings.Contains(resp.String(), "RawHttpRespons"))
	assert.Equal(t, "Marquita H Ross", response.FullName)
	assert.Equal(t, "37-47", response.AgeRange)
	assert.Equal(t, "Female", response.Gender)
	assert.Equal(t, "San Francisco, California, United States", response.Location)
	assert.Equal(t, "Senior Petroleum Manager", response.Title)
	assert.Equal(t, "Mostow Co.", response.Organization)
	assert.Equal(t, "Senior Petroleum Manager at Mostow Co.", response.Bio)
	assert.Equal(t, "https://img.fullcontact.com/sandbox/1gagrO2K67_oc5DLG_siVCpYVE5UvCu2Z.png", response.Avatar)
	assert.Equal(t, "http://marquitaas8.com/", response.Website)
	assert.Equal(t, "https://twitter.com/marqross91", response.Twitter)
	assert.Equal(t, "https://www.linkedin.com/in/marquita-ross-5b6b72192", response.Linkedin)
	assert.Equal(t, "Marquita", response.Details.Name.Given)
	assert.Equal(t, "Ross", response.Details.Name.Family)
	assert.Equal(t, "Marquita H Ross", response.Details.Name.Full)
	assert.Equal(t, "35-44", response.Details.Age.Range)
	assert.Equal(t, 42, response.Details.Age.Value)
	assert.Equal(t, "Female", response.Details.Gender)

	assert.Equal(t, "3", response.Details.Household.FamilyInfo.HouseholdSize)
	assert.Equal(t, "2", response.Details.Household.FamilyInfo.NumberOfAdults)
	assert.Equal(t, "1", response.Details.Household.FamilyInfo.NumberOfChildren)
	assert.Equal(t, "babyBoomers", response.Details.Household.FamilyInfo.LifeCycles.BabyBoomers)
	assert.Equal(t, "dualIncomeNoKids", response.Details.Household.FamilyInfo.LifeCycles.DualIncomeNoKids)
	assert.Equal(t, "familyTies", response.Details.Household.FamilyInfo.LifeCycles.FamilyTies)
	assert.Equal(t, "generationX", response.Details.Household.FamilyInfo.LifeCycles.GenerationX)
	assert.Equal(t, "millenials", response.Details.Household.FamilyInfo.LifeCycles.Millenials)
	assert.Equal(t, "millenialsButFirstLetMeTakeASelfie", response.Details.Household.FamilyInfo.LifeCycles.MillenialsButFirstLetMeTakeASelfie)
	assert.Equal(t, "millenialsGettinHitched", response.Details.Household.FamilyInfo.LifeCycles.MillenialsGettinHitched)
	assert.Equal(t, "millenialsIAmAnAdult", response.Details.Household.FamilyInfo.LifeCycles.MillenialsIAmAnAdult)
	assert.Equal(t, "millenialsLivesWithMom", response.Details.Household.FamilyInfo.LifeCycles.MillenialsLivesWithMom)
	assert.Equal(t, "millenialsMomLife", response.Details.Household.FamilyInfo.LifeCycles.MillenialsMomLife)
	assert.Equal(t, "millenialsPuttingDownRoots", response.Details.Household.FamilyInfo.LifeCycles.MillenialsPuttingDownRoots)

	assert.Equal(t, "Multi Family Dwelling/Apartment", response.Details.Household.HomeInfo.DwellingType)
	assert.Equal(t, "yes", response.Details.Household.HomeInfo.DwellingTypeIndicator)
	assert.Equal(t, "no", response.Details.Household.HomeInfo.HouseholdEducation)
	assert.Equal(t, "yes", response.Details.Household.HomeInfo.HouseholdEducationIndicator)
	assert.Equal(t, "single", response.Details.Household.HomeInfo.MaritalStatus)
	assert.Equal(t, "3", response.Details.Household.HomeInfo.LengthOfResidence)
	assert.Equal(t, "yes", response.Details.Household.HomeInfo.LengthOfResidenceIndicator)
	assert.Equal(t, "no", response.Details.Household.HomeInfo.Affluents)
	assert.Equal(t, "100000", response.Details.Household.HomeInfo.CurrentLoanToValue)
	assert.Equal(t, "yes", response.Details.Household.HomeInfo.HomeHeatSource)
	assert.Equal(t, "no", response.Details.Household.HomeInfo.HouseholdOccupation)
	assert.Equal(t, "2", response.Details.Household.HomeInfo.FamilyComposition)
	assert.Equal(t, "100000", response.Details.Household.HomeInfo.HomeMarketValue)
	assert.Equal(t, "no", response.Details.Household.HomeInfo.OwnerToOwner)
	assert.Equal(t, "no", response.Details.Household.HomeInfo.RentertoOwner)
	assert.Equal(t, "2022", response.Details.Household.HomeInfo.YearHomeBuilt)

	assert.Equal(t, "PO Box", response.Details.Household.LocationInfo.CarrierRoute)
	assert.Equal(t, "807", response.Details.Household.LocationInfo.BlockGroupNumber)
	assert.Equal(t, "41860 - San Francisco-Oakland-Hayward, CA Metropolitan Statistical Area", response.Details.Household.LocationInfo.CoreBasedStatisticalArea)
	assert.Equal(t, "B - All counties in the next largest set of metropolitan areas which toher account for 30% of U.S. households according to the 2000 Census. No non-metropolitan counties qualify as A or B counties.", response.Details.Household.LocationInfo.NielsenCountySize)
	assert.Equal(t, "B", response.Details.Household.LocationInfo.NielsenCountySizeCode)
	assert.Equal(t, "SFF", response.Details.Household.LocationInfo.CensusTractSuffix)
	assert.Equal(t, "455", response.Details.Household.LocationInfo.DsfSeasonCode)
	assert.Equal(t, "US", response.Details.Household.LocationInfo.CountyCode)

	assert.Equal(t, "PRESENT", response.Details.Household.Presence.PresenceOfChildren)
	assert.Equal(t, "PRESENT", response.Details.Household.Presence.PresenceOfChildrenIndicator)
	assert.Equal(t, "1", response.Details.Household.Presence.Adult.Age18to24)
	assert.Equal(t, "2", response.Details.Household.Presence.Adult.Age25to34)
	assert.Equal(t, "3", response.Details.Household.Presence.Adult.Age35to44)
	assert.Equal(t, "4", response.Details.Household.Presence.Adult.Age45to54)
	assert.Equal(t, "5", response.Details.Household.Presence.Adult.Age55to64)
	assert.Equal(t, "6", response.Details.Household.Presence.Adult.Age65to74)
	assert.Equal(t, "7", response.Details.Household.Presence.Adult.Age75above)
	assert.Equal(t, "1", response.Details.Household.Presence.Child.Age0to2)
	assert.Equal(t, "2", response.Details.Household.Presence.Child.Age3to5)
	assert.Equal(t, "3", response.Details.Household.Presence.Child.Age6to10)
	assert.Equal(t, "4", response.Details.Household.Presence.Child.Age11to15)
	assert.Equal(t, "5", response.Details.Household.Presence.Child.Age16to17)

	assert.Equal(t, "45", response.Details.Household.Finance.Income)
	assert.Equal(t, "yes", response.Details.Household.Finance.IncomeIndicator)
	assert.Equal(t, "20 Million", response.Details.Household.Finance.NarrowBandIncome)
	assert.Equal(t, "50 Million", response.Details.Household.Finance.DiscretionarySpendingIncome)
	assert.Equal(t, "200", response.Details.Household.Finance.FirstMortgageAmountInThousands)
	assert.Equal(t, "24/10/2022", response.Details.Household.Finance.HomeEquityLoanDate)
	assert.Equal(t, "yes", response.Details.Household.Finance.HomeMarketValueTaxRecord)
	assert.Equal(t, "10 Million", response.Details.Household.Finance.InvestmentResources)
	assert.Equal(t, "1 Million", response.Details.Household.Finance.LiquidResources)
	assert.Equal(t, "10", response.Details.Household.Finance.MortgageInterestRateTypeOrRefinance)
	assert.Equal(t, "200K", response.Details.Household.Finance.MortgageLiability)
	assert.Equal(t, "no", response.Details.Household.Finance.MortgageLoanTypeOrRefinance)
	assert.Equal(t, "20/10/2021", response.Details.Household.Finance.MortgageDate)
	assert.Equal(t, "no", response.Details.Household.Finance.RefinanceIndicator)
	assert.Equal(t, "0", response.Details.Household.Finance.SecondMortgageAmountInThousands)
	assert.Equal(t, "10K", response.Details.Household.Finance.ShortTermLiability)
	assert.Equal(t, "10", response.Details.Household.Finance.IncomeIndex)
	assert.Equal(t, "70 Million", response.Details.Household.Finance.NetWorth)
	assert.Equal(t, "no", response.Details.Household.Finance.WealthResources)
	assert.Equal(t, "yes", response.Details.Household.Finance.PaymentMethodCreditCard)

	assert.Equal(t, "Female", response.Details.Demographics.Gender)
	assert.Equal(t, "35-44", response.Details.Demographics.Age.Range)
	assert.Equal(t, 1, response.Details.Demographics.Age.Birthday.Day)
	assert.Equal(t, 1, response.Details.Demographics.Age.Birthday.Month)
	assert.Equal(t, 2020, response.Details.Demographics.Age.Birthday.Year)
	assert.Equal(t, "42", response.Details.Demographics.Age.ExactAge)
	assert.Equal(t, "40-42", response.Details.Demographics.Age.AgeIn2YearRanges)
	assert.Equal(t, 42, response.Details.Demographics.Age.Value)
	assert.Equal(t, "SINGLE", response.Details.Demographics.MaritalInfo.MaritalStatus)
	assert.Equal(t, "yes", response.Details.Demographics.MaritalInfo.MaritalStatusIndicator)
	assert.Equal(t, "no", response.Details.Demographics.Enthusiasts.Niches)
	assert.Equal(t, "democratic", response.Details.Demographics.Enthusiasts.PoliticalParty)
	assert.Equal(t, "yes", response.Details.Demographics.HomeInfo.HomeOwner)
	assert.Equal(t, "yes", response.Details.Demographics.HomeInfo.HomeOwnerIndicator)
	assert.Equal(t, "100", response.Details.Demographics.Consumers.ValueScore)

	assert.Equal(t, "true", response.Details.Surveys.Own.SmartPhone)
	assert.Equal(t, "true", response.Details.Surveys.Own.Cat)
	assert.Equal(t, "true", response.Details.Surveys.Own.Dog)
	assert.Equal(t, "true", response.Details.Surveys.Own.Pets)
	assert.Equal(t, "true", response.Details.Surveys.Collectibles.Any)
	assert.Equal(t, "true", response.Details.Surveys.Collectibles.ArtAntique)
	assert.Equal(t, "true", response.Details.Surveys.Collectibles.ClubContinuity)
	assert.Equal(t, "true", response.Details.Surveys.Collectibles.Dolls)
	assert.Equal(t, "true", response.Details.Surveys.Collectibles.Figurines)
	assert.Equal(t, "true", response.Details.Surveys.DietConcerns.Diet)
	assert.Equal(t, "true", response.Details.Surveys.DietConcerns.NaturalFoods)
	assert.Equal(t, "true", response.Details.Surveys.DietConcerns.WeightControl)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.Any)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.AutomotiveWork)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.Baking)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.BirdFeedingOrWatching)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.CareerAdvancementCourses)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.CigarSmoking)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.Cooking)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.Crafts)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.CulturalArtsOrEvents)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.Gardening)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.GourmetFoods)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.HomeImprovementOrDIY)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.HomeStudyCourses)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.MotorcycleRiding)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.Photography)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.Quilting)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.Scrapbooking)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.SelfImprovementCourses)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.SewingOrNeedleworkOrKnitting)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.Wine)
	assert.Equal(t, "true", response.Details.Surveys.Hobby.Woodworking)
	assert.Equal(t, "true", response.Details.Surveys.Music.Any)
	assert.Equal(t, "true", response.Details.Surveys.Music.ChristianOrGospel)
	assert.Equal(t, "true", response.Details.Surveys.Music.Classical)
	assert.Equal(t, "true", response.Details.Surveys.Music.Country)
	assert.Equal(t, "true", response.Details.Surveys.Music.Jazz)
	assert.Equal(t, "true", response.Details.Surveys.Music.RhythmAndBlues)
	assert.Equal(t, "true", response.Details.Surveys.Music.RockNRoll)
	assert.Equal(t, "true", response.Details.Surveys.Reading.BestSellingFiction)
	assert.Equal(t, "true", response.Details.Surveys.Reading.BibleOrDevotional)
	assert.Equal(t, "true", response.Details.Surveys.Reading.Books)
	assert.Equal(t, "true", response.Details.Surveys.Reading.Childrens)
	assert.Equal(t, "true", response.Details.Surveys.Reading.CookingOrCulinary)
	assert.Equal(t, "true", response.Details.Surveys.Reading.CountryOrLifestyle)
	assert.Equal(t, "true", response.Details.Surveys.Reading.Entertainment)
	assert.Equal(t, "true", response.Details.Surveys.Reading.Fashion)
	assert.Equal(t, "true", response.Details.Surveys.Reading.Interior)
	assert.Equal(t, "true", response.Details.Surveys.Reading.MedicalOrHealth)
	assert.Equal(t, "true", response.Details.Surveys.Reading.Military)
	assert.Equal(t, "true", response.Details.Surveys.Reading.Romance)
	assert.Equal(t, "true", response.Details.Surveys.Reading.Sports)
	assert.Equal(t, "true", response.Details.Surveys.Reading.WorldNews)
	assert.Equal(t, "true", response.Details.Surveys.Sporting.BigGameHunting)
	assert.Equal(t, "true", response.Details.Surveys.Sporting.BoatingOrSailing)
	assert.Equal(t, "true", response.Details.Surveys.Sporting.CampingOrHiking)
	assert.Equal(t, "true", response.Details.Surveys.Sporting.Cycling)
	assert.Equal(t, "true", response.Details.Surveys.Sporting.Fishing)
	assert.Equal(t, "true", response.Details.Surveys.Sporting.FitnessExcercise)
	assert.Equal(t, "true", response.Details.Surveys.Sporting.Golf)
	assert.Equal(t, "true", response.Details.Surveys.Sporting.HuntingOrShooting)
	assert.Equal(t, "true", response.Details.Surveys.Sporting.Nascar)
	assert.Equal(t, "true", response.Details.Surveys.Sporting.RunningOrJogging)
	assert.Equal(t, "true", response.Details.Surveys.Sporting.SkiingOrSnowboarding)
	assert.Equal(t, "true", response.Details.Surveys.Sporting.SportsMerchandiseOrActivewearRecency)
	assert.Equal(t, "true", response.Details.Surveys.Sporting.SportsParticipation)
	assert.Equal(t, "true", response.Details.Surveys.Sporting.WalkingForHealth)
	assert.Equal(t, "true", response.Details.Surveys.Sporting.YogaOrPilates)

	assert.Equal(t, "marqross91", response.Details.Profiles.Twitter.Username)
	assert.Equal(t, "Senior Petroleum Manager at Mostow Co.", response.Details.Profiles.Twitter.Bio)
	assert.Equal(t, "marquita-ross-5b6b72192", response.Details.Profiles.Linkedin.Username)
	assert.Equal(t, "http://www.pinterest.com/marquitaross006/", response.Details.Profiles.Pinterest.URL)
	assert.Equal(t, "California", response.Details.Locations[0].Region)
	assert.Equal(t, "Mostow Co.", response.Details.Employment[0].Name)
	assert.Equal(t, "https://img.fullcontact.com/sandbox/1gagrO2K67_oc5DLG_siVCpYVE5UvCu2Z.png", response.Details.Photos[0].Value)
	assert.Equal(t, "University of California, Berkeley", response.Details.Education[0].Name)
	assert.Equal(t, "http://marquitaas8.com/", response.Details.Urls[0].Value)
	assert.Equal(t, "9", response.Extended["epsilon_key_1"])
	assert.Equal(t, "Q", response.Extended["epsilon_key_3"])
}

func TestPersonEnrichAutoRetry(t *testing.T) {
	ch := make(chan *APIResponse)
	fcTestClient, testServer := getTestServerAndClient(personEnrichUrl, "", 429)
	defer testServer.Close()
	go fcTestClient.do(testServer.URL, nil, ch)
	resp := <-ch
	assert.False(t, resp.IsSuccessful)
	assert.Equal(t, 429, resp.StatusCode)
}

func TestPersonEnrichStatus400(t *testing.T) {
	ch := make(chan *APIResponse)
	fcTestClient, testServer := getTestServerAndClient(personEnrichUrl, "", 400)
	defer testServer.Close()
	go fcTestClient.do(testServer.URL, nil, ch)
	resp := <-ch
	assert.False(t, resp.IsSuccessful)
	assert.Equal(t, 400, resp.StatusCode)
}

func TestPersonEnrichStatus202(t *testing.T) {
	ch := make(chan *APIResponse)
	fcTestClient, testServer := getTestServerAndClient(personEnrichUrl, "", 202)
	defer testServer.Close()
	go fcTestClient.do(testServer.URL, nil, ch)
	resp := <-ch
	assert.True(t, resp.IsSuccessful)
	assert.Equal(t, 202, resp.StatusCode)
}

func TestPersonEnrichStatus401(t *testing.T) {
	ch := make(chan *APIResponse)
	fcTestClient, testServer := getTestServerAndClient(personEnrichUrl, "", 401)
	defer testServer.Close()
	go fcTestClient.do(testServer.URL, nil, ch)
	resp := <-ch
	assert.False(t, resp.IsSuccessful)
	assert.Equal(t, 401, resp.StatusCode)
}

func TestPersonEnrichStatus403(t *testing.T) {
	ch := make(chan *APIResponse)
	fcTestClient, testServer := getTestServerAndClient(personEnrichUrl, "", 403)
	defer testServer.Close()
	go fcTestClient.do(testServer.URL, nil, ch)
	resp := <-ch
	assert.False(t, resp.IsSuccessful)
	assert.Equal(t, 403, resp.StatusCode)
}
